tasks:
  - init: echo "CREATE DATABASE order_management" | psql && cat start/initdb/* | psql order_management
  - init: echo "CREATE DATABASE order_management_test" | psql && cat start/initdb/01-schema.sql | psql order_management_test
  - init: npm -C mocks i
    command: npm -C mocks start
  - init: npm -C api i
    command: npm -C api start
  - init: cd api && npm run
image: gitpod/workspace-postgres
