tasks:
  - init: npm -C mocks i
    command: npm -C mocks start
  - init: ./.gitpod-scripts/initialize-postgres.sh && cd start/api && npm i
    command: cd start/api && npm start
image: gitpod/workspace-postgres
